version: "3"

services:
  laravel-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PM_HOST=mysql-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
